#! /bin/bash 
###########################################
#
###########################################

# constants
export KALDI_HOME=/home/hain/workspace/stt/kaldi
#export GST_PLUGIN_PATH=$KALDI_HOME/src/gst-plugin
export PY_VENV_HOME=/home/hain/venv
export GST_PLUGIN_PATH=/home/hain/workspace/stt/gst-kaldi-nnet2-online

